### PR TITLE
npm: Upgrade (mostly dev) dependencies.

### PR DESCRIPTION
**Pull request by klardotsh**

### CODE REVIEW

**Comment by alexmv** [comment]
I don't know how to functionally review this effectively, but it seems to do what it says on the tin. :)

https://www.npmjs.com/package/ts-async-results?activeTab=versions seems to have had some changes recently (from 0.3.3 to 0.6.1-1) but I've not checked if they're compatible.  They're, oddly, not in the `master` of https://github.com/movesthatmatter/ts-async-results, just pushed as tags not on any branch.

**Comment by klardotsh** [comment]
Yeah, in retrospect I'm having my doubts about depending on `ts-async-results`: while it quickly did what I wanted in the TypeScript refactor, each Dependabot notification for updates to that library has been unreviewable (by way of changelogs not being findable). I may look into moving to https://github.com/supermacro/neverthrow or something similar in the future.

I'm not entirely certain how to best review stuff like this either: doing a bulk upgrade like this was the recommendation from [the recent CZO discussion about Dependabot overload](https://chat.zulip.org/#narrow/stream/43-automated-testing/topic/dependabot.20auto-merge.20philosophy), but this repo has no effective automated test strategy, making bulk upgrades a touch riskier than upgrades where I'm reading the changelog (or, often, the full diff) of each upgrade individually.

Things pass linting and type checking at this point in the branch history; I can do another manual test set up the same way as the tests I ran when doing the TypeScript refactor and report back.

**Comment by alexmv** [comment]
To be clear, I'm fine merging this as-is -- I was just noting that my review was not adding very much certainty.  But I don't think there's a great deal of risk in these upgrades.

**Comment by klardotsh** [comment]
This has now been regression tested via https://github.com/klardotsh/zulip-gha-playground/actions/runs/4546965169, which succeeded fully.

**Pull request merged**
