### PR TITLE
npm: migrate to package-lock.json v2 schema

### PR DESCRIPTION
**Pull request by klardotsh**
This is an automated action by the NPM CLI which migrates from the v1 spec used by NPM versions 5 and 6, to v2, which is a migratory spec used by NPM v7 (and is still readable by NPM v5/v6) [^1].

Given that NPM v6 shipped with NodeJS v14, which goes fully EOL at the end of April [^2], and given that NPM is mostly an evergreen-release project that provides best-effort-basis security-only backports to NPM versions that shipped with a maintained version of NodeJS [^3], we can expect to be free to upgrade to the v3 package-lock.json schema this upcoming summer or later.

[^1]: https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json#lockfileversion
[^2]: https://github.com/nodejs/release#release-schedule
[^3]: https://github.com/npm/cli/wiki/Support-Policy

### CODE REVIEW

**Comment by andersk** [comment]
The project doesn’t actually seem to build with Node.js 16 or 18, so we need to do more than just convert the lock file:

```console
$ npm run package

> @zulip/github-actions-zulip@1.0.0 package
> ncc build src/send-message.js -o dist/send-message

ncc: Version 0.28.6
ncc: Compiling file index.js
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at hashOf (/home/anders/zulip/github-actions-zulip/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1814625)
    at ncc (/home/anders/zulip/github-actions-zulip/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1818842)
    at runCmd (/home/anders/zulip/github-actions-zulip/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:51862)
    at 819 (/home/anders/zulip/github-actions-zulip/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:48659)
    at __webpack_require__ (/home/anders/zulip/github-actions-zulip/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:55378)
    at /home/anders/zulip/github-actions-zulip/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:55590
    at /home/anders/zulip/github-actions-zulip/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:55651
    at Object.<anonymous> (/home/anders/zulip/github-actions-zulip/node_modules/@vercel/ncc/dist/ncc/cli.js:8:28) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

When we fix this, we should also bump the version of Node we test with in CI, and the version of Node the action runs in its `action.yml`.

**Comment by klardotsh** [comment]
Since the v2 lock format is backwards-compatible, I opened this up as a bit of an independent work unit before jumping into the rest. I'm also open to the idea of closing this, getting through all of the refactor bits mentioned [in the CZO topic](https://chat.zulip.org/#narrow/stream/43-automated-testing/topic/github-actions-zulip.3A.20typescript.3F/near/1467008), and opening a (probably rather large, by then) PR of all of the resultant commits. Thoughts?

**Comment by klardotsh** [comment]
FWIW on Linux x86_64 this _does_ package for me against Node v16:

```
(woods) github-actions-zulip  » package-lock-v2 » npm run package

> @zulip/github-actions-zulip@1.0.0 package
> ncc build src/send-message.js -o dist/send-message

ncc: Version 0.28.6
ncc: Compiling file index.js
300kB  dist/send-message/index.js
300kB  [1406ms] - ncc 0.28.6
                                                                                   
(woods) github-actions-zulip  » package-lock-v2 » node --version
v16.15.1
```

So I've got some investigation to do, I suppose.

**Comment by andersk** [comment]
Interesting. I’m also on Linux x86_64, but it might be a difference in the NixOS builds of Node.js? It works with `NODE_OPTIONS=--openssl-legacy-provider`.

Upgrading to `@vercel/ncc@0.34.0` fixes the issue, so we should probably just do that.

**Comment by klardotsh** [comment]
- Updated commit messages to match zulip/zulip standards
- Took the recommended ncc upgrade and tested locally (no regressions on my Void Linux x86_64 rig with Node 16.15.1 as shown above)
- Regenerated the dist file with this new version
- Linked, in the second commit message, a relevant StackOverflow link about this OpenSSL+NodeJS quirk for ol' history's sake

**Comment by andersk** [comment]
Merged, thanks @klardotsh!

**Pull request merged**
